### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by KurtBilde** [DomGries/InnoDependencyInstaller#32]
Hi,
Would like to add Danish and MS SQL 2014 with tools as product, but unable to push and to email the author :-O
-Kurt

**Comment by kungfux** [comment]
Hi @KurtBilde,
You may go through a standard process of GitHub. Just [fork this repo](https://help.github.com/articles/fork-a-repo/) and send your [pull request](https://help.github.com/articles/about-pull-requests/).
Thanks.
